name: 'Coverage badge'

on:
  push:
    branches: [ main, beta ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '**/*.md'
  workflow_dispatch:

jobs:
  main-test:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm install
        run: |
          npm install -g npm@latest
          npm i --quiet --no-progress
          npm t
      - name: badge
        run: |
          npm run coverage-badge
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if ! git commit -m "[bot] update coverage badge"
          then
            echo "Nothing to commit, exiting action..."
          else
            git push
          fi
          
  beta-test:
    if: ${{ github.ref == 'refs/heads/beta' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'beta'
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm install
        run: |
          npm install -g npm@latest
          npm i --quiet --no-progress
          npm t
      - name: badge
        run: |
          npm run coverage-badge
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if ! git commit -m "[bot] update coverage badge"
          then
            echo "Nothing to commit, exiting action..."
          else
            git push
          fi
